version: '3.8'
services: 
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: always